[package]
name = "md-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
unicode-normalization.workspace = true
cap-std.workspace = true
cap-tempfile.workspace = true
thiserror.workspace = true
blake3.workspace = true

[dev-dependencies]
tempfile.workspace = true
